# Generated by Django 2.1.2 on 2018-11-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=40)),
                ('year', models.IntegerField(choices=[(2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024')], unique=True, verbose_name='year')),
                ('icon_type', models.CharField(choices=[('fa-building', 'Building'), ('fa-briefcase', 'Briefcase'), ('fa-chart-line', 'Chart'), ('fa-city', 'City'), ('fa-compass', 'Compass'), ('fa-home', 'Home')], max_length=40)),
                ('description', models.TextField()),
                ('background_image', models.FileField(blank=True, null=True, upload_to='roadmap_images')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
