# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 04:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='news',
            name='updated_by',
        ),
    ]
