# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20180816_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('Promo', 'Promotion'), ('Normal', 'Normal'), ('Project', 'Project')], max_length=40),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
