# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_team', '0002_auto_20180816_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='member_photo'),
        ),
    ]
