# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_team', '0003_teammember_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='full_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='linkedin',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.CharField(choices=[('Executive', 'Excutive'), ('Advisor', 'Advisor'), ('Technical', 'Technical')], max_length=40),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
