# Generated by Django 2.0.4 on 2018-09-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_team', '0005_auto_20180918_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.CharField(choices=[('Core', 'Core Team'), ('Advisor', 'Advisor'), ('Partner', 'Partner')], max_length=40),
        ),
    ]
