# Generated by Django 2.1.2 on 2018-11-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('the_problem', models.TextField()),
                ('the_solution', models.TextField()),
                ('slider_image', models.FileField(upload_to='slider_images')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
