# Generated by Django 2.1.2 on 2018-11-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='slider_name',
            field=models.CharField(default='null', max_length=40),
            preserve_default=False,
        ),
    ]
